--
-- PostgreSQL database dump
--

\restrict Bj159hB5467D8Z1WJR9vyFPcbVHYCkKwzfGPEZFaImCdOU5L7qdFdZLP99JESaZ

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: group_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_members (
    id bigint NOT NULL,
    group_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role character varying(20) NOT NULL,
    joined_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: group_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.group_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: group_memories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_memories (
    group_id bigint NOT NULL,
    summary text NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: meeting_available_dates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meeting_available_dates (
    id bigint NOT NULL,
    meeting_participant_id bigint NOT NULL,
    available_date date NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: meeting_available_dates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meeting_available_dates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meeting_available_dates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meeting_calendar_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meeting_calendar_events (
    id bigint NOT NULL,
    meeting_id bigint NOT NULL,
    user_id bigint NOT NULL,
    google_event_id character varying(255),
    status character varying(30) NOT NULL,
    failure_reason character varying(500),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: meeting_calendar_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meeting_calendar_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meeting_calendar_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meeting_chat_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meeting_chat_messages (
    id bigint NOT NULL,
    meeting_id bigint NOT NULL,
    role character varying(20) NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: meeting_chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meeting_chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meeting_chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meeting_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meeting_groups (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    invite_code character varying(8) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: meeting_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meeting_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meeting_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meeting_memories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meeting_memories (
    meeting_id bigint NOT NULL,
    memory jsonb NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: meeting_participants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meeting_participants (
    id bigint NOT NULL,
    meeting_id bigint NOT NULL,
    group_member_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    availability_submitted_at timestamp with time zone
);


--
-- Name: meeting_participants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meeting_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meeting_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meeting_suggestions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meeting_suggestions (
    id bigint NOT NULL,
    meeting_id bigint NOT NULL,
    generation integer NOT NULL,
    rank integer NOT NULL,
    external_place_id character varying(100) NOT NULL,
    category character varying(100) NOT NULL,
    place_provider character varying(30) NOT NULL,
    name character varying(255) NOT NULL,
    address character varying(500) NOT NULL,
    external_url text,
    proposed_start_at timestamp with time zone NOT NULL,
    proposed_end_at timestamp with time zone NOT NULL,
    reasons jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    business_hours character varying(500),
    business_hours_verified boolean DEFAULT false NOT NULL,
    open_at_meeting_time boolean
);


--
-- Name: meeting_suggestions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meeting_suggestions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meeting_suggestions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meetings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meetings (
    id bigint NOT NULL,
    group_id bigint NOT NULL,
    created_by bigint NOT NULL,
    purpose character varying(1000),
    region character varying(100),
    schedule_search_from date,
    schedule_search_to date,
    preferred_time_of_day character varying(30),
    status character varying(30) NOT NULL,
    confirmed_start_at timestamp with time zone,
    confirmed_end_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    confirmed_suggestion_id bigint,
    resolved_start_at timestamp with time zone,
    resolved_end_at timestamp with time zone
);


--
-- Name: meetings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meetings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meetings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: preference_vocabulary; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.preference_vocabulary (
    id bigint NOT NULL,
    code character varying(100) NOT NULL,
    domain character varying(50) NOT NULL,
    parent_code character varying(100),
    display_name character varying(100) NOT NULL
);


--
-- Name: preference_vocabulary_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.preference_vocabulary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.preference_vocabulary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_preferences (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    vocabulary_code character varying(100) NOT NULL,
    raw_value character varying(255) NOT NULL,
    sentiment character varying(20) NOT NULL,
    strength character varying(20) NOT NULL,
    mapping_type character varying(20) NOT NULL,
    source_text text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: user_preferences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    google_subject character varying(255) NOT NULL,
    email character varying(320) NOT NULL,
    nickname character varying(50),
    onboarding_completed boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: group_members group_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_pkey PRIMARY KEY (id);


--
-- Name: group_memories group_memories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_memories
    ADD CONSTRAINT group_memories_pkey PRIMARY KEY (group_id);


--
-- Name: meeting_available_dates meeting_available_dates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_available_dates
    ADD CONSTRAINT meeting_available_dates_pkey PRIMARY KEY (id);


--
-- Name: meeting_calendar_events meeting_calendar_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_calendar_events
    ADD CONSTRAINT meeting_calendar_events_pkey PRIMARY KEY (id);


--
-- Name: meeting_chat_messages meeting_chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_chat_messages
    ADD CONSTRAINT meeting_chat_messages_pkey PRIMARY KEY (id);


--
-- Name: meeting_groups meeting_groups_invite_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_groups
    ADD CONSTRAINT meeting_groups_invite_code_key UNIQUE (invite_code);


--
-- Name: meeting_groups meeting_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_groups
    ADD CONSTRAINT meeting_groups_pkey PRIMARY KEY (id);


--
-- Name: meeting_memories meeting_memories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_memories
    ADD CONSTRAINT meeting_memories_pkey PRIMARY KEY (meeting_id);


--
-- Name: meeting_participants meeting_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_participants
    ADD CONSTRAINT meeting_participants_pkey PRIMARY KEY (id);


--
-- Name: meeting_suggestions meeting_suggestions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_suggestions
    ADD CONSTRAINT meeting_suggestions_pkey PRIMARY KEY (id);


--
-- Name: meetings meetings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT meetings_pkey PRIMARY KEY (id);


--
-- Name: preference_vocabulary preference_vocabulary_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.preference_vocabulary
    ADD CONSTRAINT preference_vocabulary_code_key UNIQUE (code);


--
-- Name: preference_vocabulary preference_vocabulary_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.preference_vocabulary
    ADD CONSTRAINT preference_vocabulary_pkey PRIMARY KEY (id);


--
-- Name: group_members uk_group_members_group_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT uk_group_members_group_user UNIQUE (group_id, user_id);


--
-- Name: meeting_available_dates uk_meeting_available_dates_participant_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_available_dates
    ADD CONSTRAINT uk_meeting_available_dates_participant_date UNIQUE (meeting_participant_id, available_date);


--
-- Name: meeting_calendar_events uk_meeting_calendar_events_meeting_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_calendar_events
    ADD CONSTRAINT uk_meeting_calendar_events_meeting_user UNIQUE (meeting_id, user_id);


--
-- Name: meeting_participants uk_meeting_participants_meeting_member; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_participants
    ADD CONSTRAINT uk_meeting_participants_meeting_member UNIQUE (meeting_id, group_member_id);


--
-- Name: meeting_suggestions uk_meeting_suggestions_generation_place; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_suggestions
    ADD CONSTRAINT uk_meeting_suggestions_generation_place UNIQUE (meeting_id, generation, external_place_id);


--
-- Name: meeting_suggestions uk_meeting_suggestions_generation_rank; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_suggestions
    ADD CONSTRAINT uk_meeting_suggestions_generation_rank UNIQUE (meeting_id, generation, rank);


--
-- Name: user_preferences uk_user_preferences_user_vocabulary; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT uk_user_preferences_user_vocabulary UNIQUE (user_id, vocabulary_code);


--
-- Name: user_preferences user_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_google_subject_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_google_subject_key UNIQUE (google_subject);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_group_members_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_group_members_user_id ON public.group_members USING btree (user_id);


--
-- Name: idx_meeting_available_dates_participant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_meeting_available_dates_participant ON public.meeting_available_dates USING btree (meeting_participant_id, available_date);


--
-- Name: idx_meeting_calendar_events_meeting_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_meeting_calendar_events_meeting_id ON public.meeting_calendar_events USING btree (meeting_id);


--
-- Name: idx_meeting_chat_messages_meeting; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_meeting_chat_messages_meeting ON public.meeting_chat_messages USING btree (meeting_id, id);


--
-- Name: idx_meeting_participants_member_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_meeting_participants_member_id ON public.meeting_participants USING btree (group_member_id);


--
-- Name: idx_meeting_suggestions_meeting_generation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_meeting_suggestions_meeting_generation ON public.meeting_suggestions USING btree (meeting_id, generation DESC);


--
-- Name: idx_meetings_group_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_meetings_group_id ON public.meetings USING btree (group_id);


--
-- Name: idx_meetings_upcoming; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_meetings_upcoming ON public.meetings USING btree (group_id, confirmed_start_at) WHERE ((status)::text = 'CONFIRMED'::text);


--
-- Name: idx_user_preferences_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_preferences_user_id ON public.user_preferences USING btree (user_id);


--
-- Name: uk_group_members_single_host; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_group_members_single_host ON public.group_members USING btree (group_id) WHERE ((role)::text = 'HOST'::text);


--
-- Name: group_members group_members_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.meeting_groups(id);


--
-- Name: group_members group_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: group_memories group_memories_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_memories
    ADD CONSTRAINT group_memories_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.meeting_groups(id) ON DELETE CASCADE;


--
-- Name: meeting_available_dates meeting_available_dates_meeting_participant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_available_dates
    ADD CONSTRAINT meeting_available_dates_meeting_participant_id_fkey FOREIGN KEY (meeting_participant_id) REFERENCES public.meeting_participants(id) ON DELETE CASCADE;


--
-- Name: meeting_calendar_events meeting_calendar_events_meeting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_calendar_events
    ADD CONSTRAINT meeting_calendar_events_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.meetings(id) ON DELETE CASCADE;


--
-- Name: meeting_calendar_events meeting_calendar_events_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_calendar_events
    ADD CONSTRAINT meeting_calendar_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: meeting_chat_messages meeting_chat_messages_meeting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_chat_messages
    ADD CONSTRAINT meeting_chat_messages_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.meetings(id) ON DELETE CASCADE;


--
-- Name: meeting_memories meeting_memories_meeting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_memories
    ADD CONSTRAINT meeting_memories_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.meetings(id) ON DELETE CASCADE;


--
-- Name: meeting_participants meeting_participants_group_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_participants
    ADD CONSTRAINT meeting_participants_group_member_id_fkey FOREIGN KEY (group_member_id) REFERENCES public.group_members(id);


--
-- Name: meeting_participants meeting_participants_meeting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_participants
    ADD CONSTRAINT meeting_participants_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.meetings(id) ON DELETE CASCADE;


--
-- Name: meeting_suggestions meeting_suggestions_meeting_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meeting_suggestions
    ADD CONSTRAINT meeting_suggestions_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.meetings(id) ON DELETE CASCADE;


--
-- Name: meetings meetings_confirmed_suggestion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT meetings_confirmed_suggestion_id_fkey FOREIGN KEY (confirmed_suggestion_id) REFERENCES public.meeting_suggestions(id);


--
-- Name: meetings meetings_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT meetings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: meetings meetings_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT meetings_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.meeting_groups(id);


--
-- Name: preference_vocabulary preference_vocabulary_parent_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.preference_vocabulary
    ADD CONSTRAINT preference_vocabulary_parent_code_fkey FOREIGN KEY (parent_code) REFERENCES public.preference_vocabulary(code);


--
-- Name: user_preferences user_preferences_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_preferences user_preferences_vocabulary_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_vocabulary_code_fkey FOREIGN KEY (vocabulary_code) REFERENCES public.preference_vocabulary(code);


--
-- PostgreSQL database dump complete
--

\unrestrict Bj159hB5467D8Z1WJR9vyFPcbVHYCkKwzfGPEZFaImCdOU5L7qdFdZLP99JESaZ

